### ISSUE TITLE
unsupported operand type(s) for -: 'list' and 'int'

### ISSUE THREAD

**Issue by jjj-guo** [AbdullahO/mSSA#2]
hello,I've always had the bug that typing in a one-dimensional time series reports the following error:unsupported operand type(s) for -: 'list' and 'int'

**Comment by AbdullahO** [comment]
Thanks jjj-guo. Can you please give us more information to figure out the problem?  A snippet of your code that gives this error would be very helpful. 
BTW, we provide an example for a one-dimensional time series in the notebook here: 
https://github.com/AbdullahO/mSSA/blob/master/mssa/examples/mSSA_notebook_example.ipynb
Let me know if you followed the same steps and received the same error. 

Thanks.
